[project]
name = "shoe-pricer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-decouple>=3.8",
    "sqlmodel>=0.0.24",
]
